[2024-11-28T11:08:23.566+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: challenge_dag.extract_task manual__2024-11-28T11:08:21.346465+00:00 [queued]>
[2024-11-28T11:08:23.571+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: challenge_dag.extract_task manual__2024-11-28T11:08:21.346465+00:00 [queued]>
[2024-11-28T11:08:23.571+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-11-28T11:08:23.581+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): extract_task> on 2024-11-28 11:08:21.346465+00:00
[2024-11-28T11:08:23.585+0000] {standard_task_runner.py:57} INFO - Started process 47163 to run task
[2024-11-28T11:08:23.588+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'challenge_dag', 'extract_task', 'manual__2024-11-28T11:08:21.346465+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/challenge_dag.py', '--cfg-path', '/tmp/tmpf0d76u8c']
[2024-11-28T11:08:23.588+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask extract_task
[2024-11-28T11:08:23.613+0000] {task_command.py:410} INFO - Running <TaskInstance: challenge_dag.extract_task manual__2024-11-28T11:08:21.346465+00:00 [running]> on host codespaces-c5d7e2
[2024-11-28T11:08:23.660+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='challenge_dag' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-28T11:08:21.346465+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-28T11:08:21.346465+00:00'
[2024-11-28T11:08:23.661+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-28T11:08:23.661+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'wget -c https://raw.githubusercontent.com/vinooganesh/hands-on-introduction-data-engineering-4395021-data-files/main/constituents.csv -O /workspaces/hands-on-introduction-data-engineering-4395021/lab/challenge/challenge-extract-data.csv']
[2024-11-28T11:08:23.669+0000] {subprocess.py:86} INFO - Output:
[2024-11-28T11:08:23.673+0000] {subprocess.py:93} INFO - --2024-11-28 11:08:23--  https://raw.githubusercontent.com/vinooganesh/hands-on-introduction-data-engineering-4395021-data-files/main/constituents.csv
[2024-11-28T11:08:23.682+0000] {subprocess.py:93} INFO - Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.111.133, ...
[2024-11-28T11:08:23.690+0000] {subprocess.py:93} INFO - Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
[2024-11-28T11:08:23.835+0000] {subprocess.py:93} INFO - HTTP request sent, awaiting response... 404 Not Found
[2024-11-28T11:08:23.836+0000] {subprocess.py:93} INFO - 2024-11-28 11:08:23 ERROR 404: Not Found.
[2024-11-28T11:08:23.836+0000] {subprocess.py:93} INFO - 
[2024-11-28T11:08:23.837+0000] {subprocess.py:97} INFO - Command exited with return code 8
[2024-11-28T11:08:23.842+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 8.
[2024-11-28T11:08:23.844+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=challenge_dag, task_id=extract_task, execution_date=20241128T110821, start_date=20241128T110823, end_date=20241128T110823
[2024-11-28T11:08:23.855+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 12 for task extract_task (Bash command failed. The command returned a non-zero exit code 8.; 47163)
[2024-11-28T11:08:23.880+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-11-28T11:08:23.893+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
